language: java

jdk:
  - oraclejdk8

# Required when using Docker
sudo: true

services:
  - docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email: false

# --quiet for less verbose logs
script: mvn clean verify  --quiet