version: '3'

services:
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  question:
    build:
      context: question
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  quiz:
    build:
      context: quiz
      dockerfile: Dockerfile
    ports:
      - "8081:8080"