version: '3.3'

services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - eureka
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  game-server:
    build:
      context: game
      dockerfile: Dockerfile
    depends_on:
      - gateway
  player-server:
    build:
      context: player
      dockerfile: Dockerfile
    depends_on:
      - gateway
  quiz-server-0:
    build:
      context: quiz
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=A
    depends_on:
      - gateway
  quiz-server-1:
    build:
      context: quiz
      dockerfile: Dockerfile
    environment:
      - SERVICE_ID=B
    depends_on:
      - gateway