version: '3.3'

services:
  #Data storage
  redis:
    image: "redis:latest"
  postgres-quiz:
    image: "postgres:10"
  postgres-game:
    image: "postgres:10"
  postgres-player:
    image: "postgres:10"

  #Service
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  game-server:
    build:
      context: game
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - postgres-game
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  player-server:
    build:
      context: player
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - postgres-player
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  quiz-server-0:
    build:
      context: quiz
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_ID=A
    depends_on:
      - gateway
      - postgres-quiz
  quiz-server-1:
    build:
      context: quiz
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_ID=B
    depends_on:
      - gateway
      - postgres-quiz