version: '3'

services:
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  question1:
    build:
      context: question
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PRODUCER_ID=Question1
    depends_on:
      - eureka
  question2:
    build:
      context: question
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PRODUCER_ID=Question2
    depends_on:
      - eureka
  quiz:
    build:
      context: quiz
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - eureka