version: '3.3'

services:
  #Data storage
  redis:
    image: "redis:latest"
  postgres-quiz:
    image: "postgres:10"
  postgres-game:
    image: "postgres:10"
  postgres-score:
    image: "postgres:10"

  #Message queue
  rabbitmq:
    image:  "rabbitmq:3"

  #Custom service
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  game-server:
    build:
      context: game
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - postgres-game
      - redis
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  quiz-server-0:
    build:
      context: quiz
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_ID=A
    depends_on:
      - gateway
      - postgres-quiz
      - redis
  quiz-server-1:
    build:
      context: quiz
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_ID=B
    depends_on:
      - gateway
      - postgres-quiz
      - redis
  score-server:
    build:
      context: score
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - gateway
      - postgres-score
      - redis
      - rabbitmq