version: '3'

services:
  question:
    build:
      context: question
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  quiz:
    build:
      context: quiz
      dockerfile: Dockerfile
    ports:
      - "8081:8081"