version: '3.3'

services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - eureka
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  game:
    build:
      context: game
      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
    depends_on:
      - gateway
  player:
    build:
      context: player
      dockerfile: Dockerfile
#    ports:
#      - "8081:8080"
    depends_on:
      - gateway
  quiz1:
    build:
      context: quiz
      dockerfile: Dockerfile
#    ports:
#      - "8090:8080"
    environment:
      - SERVICE_ID=quiz1
    depends_on:
      - gateway
  quiz2:
    build:
      context: quiz
      dockerfile: Dockerfile
#    ports:
#      - "8091:8080"
    environment:
      - SERVICE_ID=quiz2
    depends_on:
      - gateway