server:
  contextPath: /quizexercise/api
  port: 8080

#Todo: Investigate docker and DBs
#spring:
#  application:
#    name: quiz-server
#  datasource:
#    url: "jdbc:h2:mem:"
#    driver-class-name: "org.h2.Driver"
#  jpa:
#    database: "h2"
#    hibernate:
#      ddl-auto: "create-drop"