server:
  port: 80

spring:
  application:
    name: gateway
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

zuul:
  routes:
    quiz-server:
      path: /quiz-server/**
    game-server:
      path: /game-server/**
  sensitive-headers:

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  sessions: ALWAYS

logging:
  level:
    org.springframework.security: debug