spring:
  application:
    name: gateway
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

zuul:
  routes:
    category:
      path: /categories/**
      sensitive-headers:
    question:
      path: /questions/**
      sensitive-headers:
    quiz:
      path: /quizzes/**
      sensitive-headers:
    game:
      path: /games/**
      sensitive-headers:

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  sessions: ALWAYS