server:
  port: 80

spring:
  application:
    name: gateway
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

zuul:
  routes:
    category:
      path: /categories/**
    question:
      path: /questions/**
    quiz:
      path: /quizzes/**
    game:
      path: /games/**
  sensitive-headers:
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  sessions: ALWAYS

logging:
  level:
    org.springframework.security: debug