server:
  port: 8761 #Unsure if mandatory

eureka:
  instance:
    hostname: eureka #Unsure if mandatory
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #Unsure if mandatory